#!/usr/bin/env bash
# The engineer's entry point for building one image. Submits the job;
# scripts/build-image.sh is what runs.
#
#   submit-build-image.sh [--cpus N] [--mem SIZE] [--time HH:MM:SS] \
#       [--partition NAME] [--dry-run] <family>/<app>
#
# An image build is a solver run and a filesystem unpack -- compute work that
# does not belong on a login node -- and Apptainer is not on a login node's PATH
# without Spack. This wrapper removes both concerns from whoever is building:
# the job runs on a compute node, and build-image.sh resolves Apptainer itself.
set -uo pipefail

this_script="scripts/submit-build-image.sh"

log() {
    echo -e "[$(date -Iseconds)][${this_script}] $1"
}

fail() {
    log "ERROR: $1"
    exit 1
}

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)

usage() {
    echo "usage: $0 [--cpus N] [--mem SIZE] [--time HH:MM:SS] [--partition NAME] [--dry-run] <family>/<app>" >&2
    echo "  e.g. $0 jupyter-codeserver-ai/jupyterlab" >&2
    exit 64
}

# Defaults sized for a full conda solve and unpack. Every one is overridable,
# because what is generous on one partition is a rejected job on another.
CPUS=8
MEM=16G
TIME=02:00:00
PARTITION=""
DRY_RUN=0
TARGET=""

while [ $# -gt 0 ]; do
    case "$1" in
        --cpus)      [ $# -ge 2 ] || usage; CPUS="$2"; shift 2 ;;
        --mem)       [ $# -ge 2 ] || usage; MEM="$2"; shift 2 ;;
        --time)      [ $# -ge 2 ] || usage; TIME="$2"; shift 2 ;;
        --partition) [ $# -ge 2 ] || usage; PARTITION="$2"; shift 2 ;;
        --dry-run)   DRY_RUN=1; shift ;;
        -*)          usage ;;
        *)           [ -z "$TARGET" ] || usage; TARGET="$1"; shift ;;
    esac
done

[ -n "$TARGET" ] || usage

FAMILY="${TARGET%%/*}"
APP="${TARGET##*/}"
[ -n "$FAMILY" ] && [ -n "$APP" ] && [ "$FAMILY" != "$TARGET" ] || usage

# Both checks below are build-image.sh's too. They are repeated here so they
# fail in the caller's terminal now, rather than in a log after a queue wait.
DEF="${REPO_ROOT}/images/${FAMILY}/${APP}/${APP}.def"
[ -f "$DEF" ] || fail "no image definition at '${DEF}'"

if [ -n "$(cd "$REPO_ROOT" && git status --porcelain)" ]; then
    (cd "$REPO_ROOT" && git status --short) >&2
    fail "worktree is dirty; a release artifact must be traceable to a commit"
fi

BUILD_SCRATCH="${OOD_APPTAINER_BUILD_SCRATCH:-/scratch/$(id -nu)/apptainer-build}"
SLURM_LOG="${BUILD_SCRATCH}/logs/${FAMILY}-${APP}.log"

# A thin shim by design: build-image.sh resolves Apptainer through
# lc_apptainer_bin, so nothing here activates Spack and there is only one place
# that knows how Apptainer is found.
JOB_SCRIPT_CONTENT=$(cat <<EOF
#!/usr/bin/env bash
# Generated by ${this_script}. Runs on a compute node.
set -uo pipefail

bash "${REPO_ROOT}/scripts/build-image.sh" "${TARGET}"
status=\$?
echo "build-image.sh exited with status \${status}"
exit "\${status}"
EOF
)

if [ "$DRY_RUN" -eq 1 ]; then
    printf '%s\n' "$JOB_SCRIPT_CONTENT"
    exit 0
fi

mkdir -p "$(dirname "$SLURM_LOG")" \
    || fail "cannot create the log directory '$(dirname "$SLURM_LOG")'"

JOB_SCRIPT_FILE=$(mktemp "${BUILD_SCRATCH}/logs/build-XXXXXX.sh") \
    || fail "cannot create a temporary job script under '${BUILD_SCRATCH}/logs'"
trap 'rm -f "$JOB_SCRIPT_FILE"' EXIT
printf '%s\n' "$JOB_SCRIPT_CONTENT" > "$JOB_SCRIPT_FILE"

PARTITION_FLAG=()
[ -n "$PARTITION" ] && PARTITION_FLAG=(--partition="$PARTITION")

log "submitting build job for '${TARGET}' (Slurm log: ${SLURM_LOG})"
sbatch \
    --job-name="build-image-${FAMILY}-${APP}" \
    --output="$SLURM_LOG" \
    --cpus-per-task="$CPUS" \
    --mem="$MEM" \
    --time="$TIME" \
    "${PARTITION_FLAG[@]}" \
    "$JOB_SCRIPT_FILE"
status=$?

if [ "$status" -ne 0 ]; then
    log "ERROR: failed to submit build job (exit ${status})"
    exit "$status"
fi

log "build job submitted successfully; check status with: squeue -u $(id -nu) -n build-image-${FAMILY}-${APP}"
